namespace TopGpuMining.Core.Helpers
{
    public static class CryptoUtils
    {
        public static double CalculateCoinRevenuePerDayByUsd(double blockTimeInSeconds, double blockReward, double netHashInMegaHashesPerSecond, double hashRateInMegaHashesPerSecond, double singleCoinUsdPrice)
        {
            return CalculateCoinRevenuePerDayByNethashAndBlockTime(blockTimeInSeconds, blockReward, netHashInMegaHashesPerSecond, hashRateInMegaHashesPerSecond) * singleCoinUsdPrice;
        }
        public static double CalculateCoinRevenuePerDayByBTC(double blockTimeInSeconds, double blockReward, double netHashInMegaHashesPerSecond, double hashRateInMegaHashesPerSecond, double singleCoinBtcPrice)
        {
            return CalculateCoinRevenuePerDayByNethashAndBlockTime(blockTimeInSeconds, blockReward, netHashInMegaHashesPerSecond, hashRateInMegaHashesPerSecond) * singleCoinBtcPrice;
        }
        public static double CalculateCoinRevenuePerDayByNethashAndBlockTime(double blockTimeInSeconds, double blockReward, double netHashInMegaHashesPerSecond, double hashRateInMegaHashesPerSecond)
        {

            double secondsInADay = 86400;
            //Total Coins generated by the network in a day
            double totalCoinsByNetworkInADay = secondsInADay / blockTimeInSeconds * blockReward;
            //now we want to see the percentage of the provided hash rate (our hashrate) with respect to the net hash
            double hashRateRatio = hashRateInMegaHashesPerSecond / netHashInMegaHashesPerSecond;
            //now multiply the ratio by the total coins in a day

            double coinsPerDay = hashRateRatio * totalCoinsByNetworkInADay;
            return coinsPerDay;
        }
    }

}
